# Generated by Django 4.1.3 on 2022-12-05 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа тестов',
                'verbose_name_plural': 'Группы тестов',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание теста')),
                ('groups', models.ManyToManyField(blank=True, null=True, to='core.testgroupmodel', verbose_name='Принадлежность к группам')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('correct_answers', models.IntegerField(verbose_name='Количество правильных ответов')),
                ('wrong_answers', models.IntegerField(verbose_name='Количество неправильных ответов')),
                ('is_completed', models.BooleanField(verbose_name='Корректно завершен')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testmodel', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Текст вопроса')),
                ('position', models.IntegerField(verbose_name='Позиция вопроса в тесте')),
                ('visibility', models.BooleanField(default=True, verbose_name='Видимость вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testmodel', verbose_name='Принадлежность к тесту')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Текст ответа')),
                ('is_right', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionmodel', verbose_name='Принадлежность к вопросу')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
