# Generated by Django 4.1.3 on 2022-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testmodel_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingmodel',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='Тестирование начато'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='position',
            field=models.IntegerField(default=999, verbose_name='Позиция вопроса в тесте'),
        ),
        migrations.AlterField(
            model_name='testingmodel',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Тестирование завершено'),
        ),
    ]
