# Generated by Django 4.1.3 on 2022-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testingmodel_is_start_alter_questionmodel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingmodel',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='Количество правильных ответов'),
        ),
        migrations.AlterField(
            model_name='testingmodel',
            name='wrong_answers',
            field=models.IntegerField(default=0, verbose_name='Количество неправильных ответов'),
        ),
    ]
